name: ogios_sutils
description: For easier use of socket data transmit, including SocketBuffer, In and Out.
version: 0.0.2
homepage: https://github.com/ogios/sutils-dart

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
